//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fund> funds { get; set; }
        public virtual DbSet<pay> pays { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<recipt> recipts { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<TGReturn> TGReturns { get; set; }
        public virtual DbSet<TKReturn> TKReturns { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
    }
}
