//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int id { get; set; }
        public string purchase_id { get; set; }
        public string purchase_source { get; set; }
        public string purchase_worker_id { get; set; }
        public string purchase_data { get; set; }
        public string purchase_name { get; set; }
        public string purchase_unit { get; set; }
        public Nullable<decimal> purchase_number { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> purchase_real_price { get; set; }
        public string purchase_others { get; set; }
        public Nullable<decimal> purchase_whole_price { get; set; }
        public string purchase_date { get; set; }
        public string purchase_size { get; set; }
        public string purchase_code { get; set; }
    }
}
