//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int id { get; set; }
        public string sales_id { get; set; }
        public string sales_whereabouts { get; set; }
        public string sales_worker_id { get; set; }
        public string sales_data { get; set; }
        public string sales_name { get; set; }
        public string sales_unit { get; set; }
        public Nullable<decimal> sales_number { get; set; }
        public Nullable<decimal> sales_price { get; set; }
        public Nullable<decimal> sales_real_price { get; set; }
        public string sales_others { get; set; }
        public Nullable<decimal> sales_whole_price { get; set; }
    }
}
