//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGReturn
    {
        public int id { get; set; }
        public string TGReturns_id { get; set; }
        public string TGReturns_purchaseid { get; set; }
        public string TGReturns_source { get; set; }
        public string TGReturns_worker_id { get; set; }
        public string TGReturns_data { get; set; }
        public string TGReturns_name { get; set; }
        public string TGreturns_unit { get; set; }
        public Nullable<decimal> TGReturns_number { get; set; }
        public Nullable<decimal> TGReturns_price { get; set; }
        public string TGReturns_others { get; set; }
    }
}
