//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKReturn
    {
        public int id { get; set; }
        public string TKReturns_id { get; set; }
        public string TKReturns_salesid { get; set; }
        public string TKReturns_worker_id { get; set; }
        public string TKReturns_data { get; set; }
        public string TKReturns_name { get; set; }
        public string TKReturns_unit { get; set; }
        public Nullable<decimal> TKReturns_price { get; set; }
        public Nullable<decimal> TKReturns_number { get; set; }
        public string TKReturns_others { get; set; }
    }
}
