//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string users_workid { get; set; }
        public string users_password { get; set; }
        public string users_level { get; set; }
        public string users_name { get; set; }
        public string users_sex { get; set; }
        public string users_id { get; set; }
    }
}
