//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public int warehouse_id { get; set; }
        public string warehouse_name { get; set; }
        public string warehouse_unit { get; set; }
        public Nullable<decimal> warehouse_number { get; set; }
        public Nullable<decimal> warehouse_price { get; set; }
        public string warehouse_others { get; set; }
    }
}
